DROP TABLE IF EXISTS CHANNELS;
CREATE TABLE CHANNELS
(
    ID          INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME        CHARACTER VARYING(100) NOT NULL,
    DATE        DATE,
    SUBSCRIBERS INTEGER
);
DROP TABLE IF EXISTS VIDEOS;
CREATE TABLE VIDEOS
(
    ID    INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE CHARACTER VARYING(100) NOT NULL,
    VIEWS INTEGER,
    LINK  VARCHAR,
    GENRE VARCHAR(50)
);